### ISSUE TITLE
Additional controls via fullscreen image (enhancement/suggestion)

### ISSUE THREAD

**Issue by goopen** [owncloud/gallery#660] opened 2016-06-01 13:32 UTC
I believe that it should be possible to delete pictures when viewing them via fullscreen on the web.
### Expected behaviour
1. Browsing those beautiful fullscreen pictures
2. See a blurred broken image, decide to delete, press delete or trashbin icon
3. picture is removed.

Perhaps additional information can be displayed alongside the picture as mentioned here: https://github.com/owncloud/gallery/issues/550

**Comment by oparoz** [comment] 2016-06-01 14:19
Duplicate of #/649

Please test this PR: #658

**Closed as completed by oparoz** 2016-06-01 14:19 UTC
