### ISSUE TITLE
Shared gallery links broke upgrading to OC8

### ISSUE THREAD

**Issue by alex197** [owncloud/gallery#160] opened 2015-02-12 15:39 UTC
I shared some links to gallery views of my folders on my OC7 installation. They are in the format https://myserver.tld/public.php?service=gallery&t=153d6c93f4ccba03153f68fb5464a44b . After upgrading to OC8, I got a file not found when trying to access these links. I figured out that they should now read https://myserver.tld/index.php/apps/gallery/public/153d6c93f4ccba03153f68fb5464a44b . I fixed this issue for my installation by writing an Apache RewriteRule for that. However, shared URLs should keep working between versions, so I consider this a bug.

The file link (https://myserver.tld/public.php?service=file&t=153d6c93f4ccba03153f68fb5464a44b) keeps working, so this seems gallery specific.

**Comment by martin-rueegg** [comment] 2015-02-12 23:39
alex, would you mind sharing your redirect roule?

i have actually the same issue. but your workaround does not work for me (i get "file not found").

**Comment by alex197** [comment] 2015-02-13 09:31
Yes, sure... In my `owncloud/.htaccess`, I added the following two lines right after `RewriteEngine on`:

    RewriteCond %{QUERY_STRING} ^service=gallery&t=([a-f0-9]+)$
    RewriteRule ^public\.php  /index.php/apps/gallery/public/%1? [R=301,L]

**Comment by martin-rueegg** [comment] 2015-02-13 11:10
great, thanks. unfortunately it still doesen't work with me. makes also sence, since the redirection takes place at the client side, so there is just an other request. similar to when i enter it directly into the browser's address bar.

i could not find a workaround here.

**Comment by LukasReschke** [comment] 2015-02-14 22:45
Confirmed.

**Comment by LukasReschke** [comment] 2015-02-14 22:55
Patch is at https://github.com/owncloud/gallery/pull/164 please test.

**Comment by martin-rueegg** [comment] 2015-02-15 05:44
confirm that the patch is working. thanks @LukasReschke.

**Comment by martin-rueegg** [comment] 2015-02-15 05:48
btw: the rewrite rules mentioned by @alex197 are not required at my installation (8.0 upgraded from 0.7) with this patch.

**Comment by LukasReschke** [comment] 2015-02-15 12:29
Will be fixed with the next oC 8 release. Thanks for testing.

**Closed by LukasReschke** 2015-02-15 12:29 UTC
Labels: bug
