### ISSUE TITLE
Request URI too long

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/gallery#172] opened 2015-03-13 12:43 UTC
`thumbnail/batch` should use POST and not GET if there are long nested file paths the Gallery app is unusable otherwise.

cc @icewind1991

**Comment by oparoz** [comment] 2015-03-13 16:04
Not possible afaik because it's using EventSource which is GET only. Gallery needs to switch to using IDs as index.

Duplicate of #159
Planned fix in Gallery+: https://github.com/interfasys/galleryplus/issues/27

**Comment by trs998** [comment] 2015-03-24 21:11
Same problem here with 8.0.2 - in my base the URL came to 24707 bytes -[HOST]/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=[IMAGES]

So something needs to be done in terms of stage-loading this - the attempted URL contained 232 images, which seems excessive. It's somehow limited though, as 232 images is a very small percentage of those in my storage.

**Comment by mnlipp** [comment] 2015-03-30 14:20
This should actually be closed as being a duplicate of https://github.com/owncloud/gallery/issues/159.

**Closed** 2015-03-30 15:01 UTC
