### ISSUE TITLE
Error with folders only containing mp3 files

### ISSUE THREAD

**Issue by deMattin** [owncloud/gallery#73] opened 2015-03-08 18:27 UTC
If a folder only contains mp3 files the "switch to gallery button" is shown in folder view.
This isn't a problem as I already suggested in #67 to show this switch icon in any folder independent of its content.

But in case of only mp3 files, the wheel keeps spinning and browser console gives an error, if you switch to gallery+ there:

> Uncaught TypeError: Cannot read property 'length' of null

The OC error is:

> Undefined index: type at /var/www/owncloud/apps/galleryplus/controller/servicecontroller.php#296

If you copy a picture in this folder, there's no error and this picture is shown in gallery+

Correct behaviour should be to show the message "no picture found".

**Edit**: add OC error message

**Comment by oparoz** [comment] 2015-03-08 19:30
Yep, I've looked at the JS and can see why this is happening... One more argument for getting rid of that whole detection mechanism ;), but it might also be possible to re-use the list the slideshow gets if we enforce a loading order.

The undefined index is not important, but there is definitely an issue when some kind of files are buried in lower folders. This may actually be a duplicate of https://github.com/interfasys/galleryplus/issues/69

**Comment by oparoz** [comment] 2015-03-08 19:50
OK, found the fix and pushed it to master and soon the other branches

**Comment by deMattin** [comment] 2015-03-08 20:00
The fix works well and as expected!
The gallery+ switch icon is still there in file view and if you switch to gallery+ the message "No pictures found..." is shown.
Thanks for the quick fix!

**Edit:**
There is an issue with navigation in the case, the "No picture" message is shown.
The path navigation of OC isn't shown any more and you are only able to go back with browser navigation or switch the app in OC app menu.

File view (only filled with mp3):
![image](https://cloud.githubusercontent.com/assets/5565503/6547421/d304516c-c5d7-11e4-9a3f-0b8a99ba57a6.png)

Folder switched to gallery+ (only filled with mp3)::
![image](https://cloud.githubusercontent.com/assets/5565503/6547419/b51fb740-c5d7-11e4-83ad-11a313511400.png)

This is, how it should look like:
![image](https://cloud.githubusercontent.com/assets/5565503/6547701/0e6ee1ba-c5e0-11e4-8704-6cad75cd6182.png)

**Comment by oparoz** [comment] 2015-03-08 21:00
Can I ask you to open another issue for this? I'll tell you why that is and we can talk possible solutions.
I'm closing this one since it's solved.

**Closed as completed by oparoz** 2015-03-08 21:00 UTC
Labels: bug
