### ISSUE TITLE
idea to enhance the performance of the plugin

### ISSUE THREAD

**Issue by cbxk1xg** [owncloud/gallery#88] opened 2015-03-12 21:50 UTC
Hi!

I have a very complex structure of sub-folders an the content is pretty mixed up. And so I ran into the a serious performance problem. And I guess I found out what the problem is. A couple of years ago I wrote a CMS and it had a media manager. The media manager had to create the thumbnails and it stored all the meta data. The process for the "check in" of the files was very similar. And that's the thing.

My CMS created all thumbnails (different sizes!) when you uploaded an image and your plugin does it when you browse through the folders. The thing is: My code isn't any faster but the user experience is much better. Because everyone understands that the uploading part does take some time.

So I like to suggest to make this an option, please.

Best regards,
CBX

edit: just typos

**Comment by oparoz** [comment] 2015-03-12 22:47
You're right, people are hit by the thumbnail generation slow down the first time they upgrade to oC8 and every time they delete the cache and every time the need a preview of a different size, etc.

I'll mark this as a duplicate of #18 and you may want to follow those programmes: #43 https://github.com/owncloud/core/issues/13609

**Closed as completed by oparoz** 2015-03-12 22:47 UTC
