### ISSUE TITLE
 [HTTP/1.1 414 Request-URI Too Large 4ms]

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/gallery#183] opened 2015-05-06 04:28 UTC
After having migrated from v7 to v8, I get the above HTTP error when loading photos.

The HTTP request is way too large and was

```
https://cloud.binarykitchen.com/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=InstantUpload%2FIMG_20150123_200250.jpg;InstantUpload%2FIMG_20150213_092729.jpg;InstantUpload%2FIMG_20150322_142735.jpg;

<323 LINES HERE, REMOVED>

square=1&requesttoken=KZHqclbUgXQp7D3ZIHmDHBaJUFbQZD
```

**Comment by oparoz** [comment] 2015-05-06 10:33
Duplicate of https://github.com/owncloud/gallery/issues/159

You need to switch to Gallery+ to see improvements:
https://apps.owncloud.com/content/show.php/Gallery%2B?action=content&content=169116

Report here if you still have an issue while using Gallery+
https://github.com/interfasys/galleryplus/issues/27

**Closed by oparoz** 2015-05-06 10:33 UTC

**Comment by binarykitchen** [comment] 2015-05-06 21:58
But why then is owncloud still recommending the older gallery app?

**Comment by binarykitchen** [comment] 2015-05-06 21:59
And there is no documentation on how to switch to Gallery+? Are there any installation instructions how to replace the bad, older gallery app with this new one?

**Comment by oparoz** [comment] 2015-05-06 22:10
> But why then is owncloud still recommending the older gallery app?

It's more like they haven't retired the old one, because they wanted to make sure the new one didn't break things. Unfortunately, the jump to 8.x brought more issues than what the maintainer could handle (given the time he had to work on it), so it's broken for a few people (large collections, IE users)

> And there is no documentation on how to switch to Gallery+?

Actually, there is:
https://github.com/interfasys/galleryplus#installation

It's really easy, disable the original app and install the new one.

**Comment by binarykitchen** [comment] 2015-05-06 22:25
yeah, the git pull worked like a charm, thanks!

**Comment by binarykitchen** [comment] 2015-05-06 22:26
But there are some new errors, will create new tickets ...
