### ISSUE TITLE
Configure preview quality/compression

### ISSUE THREAD

**Issue by michikommader** [owncloud/gallery#478] opened 2015-12-15 08:08 UTC
Heyho! I didn't find any option to configure the quality/compression of the generated previews.
Use case: Before uploading my pictures into my cloud I already scale them down to 1920x1080 with JPEG "quality" of around 90-94. Anyway the gallery generates previews of the same size and serves them instead the original files. These generated JPEG previews show a lot poorer quality than my originals, supposedly having a quality setting of 70-80. Artefacts are easily distinguishable (on a common workstation screen) and drive me crazy! Can I change the default behaviour?

**Comment by oparoz** [comment] 2015-12-15 13:28
Hello, this is a duplicate of https://github.com/owncloud/gallery/issues/465, which then became https://github.com/owncloud/core/issues/20665

**Closed as completed by oparoz** 2015-12-15 13:28 UTC
Labels: duplicate
