### ISSUE TITLE
Keyboard navigation: esc key to close the slideshow

### ISSUE THREAD

**Issue by Visual-Notes** [owncloud/gallery#266] opened 2015-08-12 09:32 UTC
The esc key which has currently no function, should close the slideshow, since this is the default behavior of most lightboxes/slideshows.

**Comment by oparoz** [comment] 2015-08-13 19:03
Thanks for the report.

It's a duplicate of https://github.com/owncloud/gallery/issues/251

Will be in the next release.

**Closed as completed by oparoz** 2015-08-13 19:03 UTC
Labels: duplicate
