### ISSUE TITLE
Adjust sharing for 9.0

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/gallery#508] opened 2016-02-09 08:52 UTC
With https://github.com/owncloud/core/pull/22231 we drop some of the old sharing ajax calls which are still being used in the gallery.

The code has to be migrated to OCS calls.

@rullzer maybe you can help out here to get this up and running again - THX

**Comment by oparoz** [comment] 2016-02-09 13:39
@rullzer - Is it simply a matter of changing [those URLs](https://github.com/owncloud/gallery/blob/master/js/vendor/owncloud/share.js#L249) or have variables and responses changed as well?

**Comment by oparoz** [comment] 2016-02-09 13:44
OK, had a look at https://doc.owncloud.org/server/8.2/developer_manual/core/ocs-share-api.html and all the methods have to be rewritten since they use different verbs and variables.

**Comment by rullzer** [comment] 2016-02-09 13:52
No just chaning urls won't work.

However the endpoints behave somewhat similar. But yes all needs to be changed :(

**Comment by PVince81** [comment] 2016-02-23 09:40
@rullzer would it be enough to only fix the call that creates new shares to make sure they are "new-style" shares ? Or do all the calls need to be fixed ?

**Comment by rullzer** [comment] 2016-02-23 10:21
Creating, getting and modifying need to be fixed...

**Comment by rullzer** [comment] 2016-02-26 08:34
@oparoz I could help you out with the gallery sharing (for the actual POST/GET/PUT calls).

The old endpoint used the internal fileid etc. While the OCS Share API uses the path. I'm not that at home in the gallery js code. But I assume that info is available.

Also the OCS Share API depends on the id of the share to modify/delete it. So we'll need to store that as well.

**Comment by oparoz** [comment] 2016-02-26 14:36
Thanks @rullzer . I'll take a look this weekend. 

> The old endpoint used the internal fileid etc. While the OCS Share API uses the path. I'm not that at home in the gallery js code. But I assume that info is available.

The path is available (Gallery.currentAlbum), so that shouldn't be too much of a problem

> Also the OCS Share API depends on the id of the share to modify/delete it. So we'll need to store that as well.

OK, I guess, it will go like this:
1. User clicks on button
2. Make request to share API to see if share exists
3. Populate URL and cache all returned info

**Comment by rullzer** [comment] 2016-02-26 15:17
@oparoz ok let me know if you need help.

The basic flow is the same... but the calls and response differe a bit.. be sure to add ?format=json to the calls so you get json back.

**Comment by oparoz** [comment] 2016-02-26 15:29
:+1:

**Comment by oparoz** [comment] 2016-02-27 17:09
I've had a look and that class is a total mess and has to be cleaned up/rewritten:
- The mix of UI, especially Files specific elements and logic make it very difficult to decipher and alter the code
- Not all endpoints have been replaced by WebDAV endpoints. Trial and error will tell us which work and which don't any more

On top of that [the documentation](https://doc.owncloud.org/server/9.0/developer_manual/core/ocs-share-api.html) is incomplete or inaccurate compared to what I can see in the code in Files.
- No information whatsoever on ocs/v2.php
- No information on the structure of the returned data. Per example: What does a reshare look like?
- Missing parameters in some methods (probably a v1 vs v2 thing). Per example `shared_with_me` when doing a GET

**Comment by rullzer** [comment] 2016-02-27 18:26
Yep the documentation is far from complete. We are working on improving that.

> No information whatsoever on ocs/v2.php

There is no difference beside the HTTP status code. We still only have 1 version of the share API.

> No information on the structure of the returned data. Per example: What does a reshare look like?

Yep needs to be improved as well. 

Basically there are 3 fields:
- share_with: The receiving part
- uid_owner: The initiator of the share
- uid_file_owner: The owner of the files

If `uid_owner !== uid_file_woner` then it is a reshare.

> Missing parameters in some methods (probably a v1 vs v2 thing). Per example shared_with_me when doing a GET

Yeah this method was always there but since the start not documented. But most should not need it anyway. But you are right we should add it.

**Comment by rullzer** [comment] 2016-02-27 18:28
> The mix of UI, especially Files specific elements and logic make it very difficult to decipher and alter the code

Yeah that is why we moved away from it and to backbone in code

> The WebDAV endpoints are not true replacements for the ajax endpoints as it's not possible to perform a remote search any more

You mean the OCS Share API endpoint right?
There is also a `../sharee` endpoint to do search completion.

**Comment by oparoz** [comment] 2016-02-27 18:36
> > No information whatsoever on ocs/v2.php
> 
> There is no difference beside the HTTP status code. We still only have 1 version of the share API.

OK, so it's a documentation issue (which you've confirmed)

> You mean the OCS Share API endpoint right?
> There is also a ../sharee endpoint to do search completion.

I've just discovered that the migration is only partial...

We still have to use the ajax endpoints to get users and email addresses

> If uid_owner !== uid_file_woner then it is a reshare.

Thanks for confirming. That means rewriting all the code which relies on `reshare` being part of the return data.

**Comment by rullzer** [comment] 2016-02-27 19:08
@oparoz see: https://github.com/owncloud/documentation/issues/1626 for the sharee API

Also yes that changed. THis is because there are starting from 9.0 no reshares in the traditional sense. All shares are flat and reshares just have a different initiator. This so the owner always has the complete overview. See https://github.com/owncloud/core/issues/9058

**Comment by oparoz** [comment] 2016-02-27 20:16
Thanks. Since getting users works with the old endpoint, I'm not going to touch it and hopefully, by the time it's removed the templates in `core` will be fixed and offer the right sidebar with the sharing panel, otherwise I'll revisit this class.

**Comment by oparoz** [comment] 2016-02-28 20:49
> Yeah this method was always there but since the start not documented. But most should not need it anyway. But you are right we should add it.

@rullzer - Actually, you cannot retrieve files shared with you without using that parameter.

**Comment by oparoz** [comment] 2016-02-28 21:35
Hmmm... It's worse than I thought, we have to makes 2 requests in order to get all the shares. One for the shares owned by the user and one for the shares shared with the user. This defo needs to be documented and hopefully fixed in 9.1

**Comment by oparoz** [comment] 2016-02-29 16:54
Fix is in #541

**Closed as completed** 2016-03-01 11:47 UTC
Labels: bug, feature:photowall, Regression, sev1-critical, 100
