### ISSUE TITLE
Scrollbar not available for group of images shared through public share links

### ISSUE THREAD

**Issue by pako81** [owncloud/gallery#493] opened 2016-01-08 16:02 UTC
### Steps to reproduce
1. Share a group of images by using the public share link option
2. Open the shared link with different browsers (Firefox, Chrome, Internet Explorer, Safari)
### Expected behaviour

Scrollbar should be available and it should be possible to scroll down through all the images
### Actual behaviour

Scrollbar is not available and only a part of the images is actually visible
### Server configuration

**ownCloud version:** (see ownCloud admin page)

8.2.2
### Client configuration

**Browser:**

Firefox, Chrome, Internet Explorer, Safari

**Operating system:**

Windows, Mac OS X

Link to Customer's test instance having Web Theming enabled: 
https://oc.hs-osnabrueck.de/owncloud/index.php/apps/gallery/s/LuKm1opccEoSNhF#

And screenshots from another test instance without Web Theming enabled (therefore the issue seems not being related to some erroneous settings in Web Theming):

![bildschirmfoto 2016-01-08 um 14 25 07](https://cloud.githubusercontent.com/assets/12248713/12201630/ba538b76-b625-11e5-830b-dca78e8f3370.png)

![bildschirmfoto 2016-01-08 um 14 24 48](https://cloud.githubusercontent.com/assets/12248713/12201641/c866fcf2-b625-11e5-8910-ae49e20c9054.png)

From my tests scrollbar is visible however for Customer it seems to be not available.

**Comment by oparoz** [comment] 2016-01-08 16:57
Thanks for the report and especially the link, it allowed me to have a better understanding of what others were reporting.
This is a duplicate of https://github.com/owncloud/gallery/issues/490, so if it's OK with you, I'm going to close this and add the blue-ticket label to the other issue (I'm not familiar with your internal processes).

**Comment by pako81** [comment] 2016-01-08 17:01
Thanks! sure go ahead and close it.

**Comment by oparoz** [comment] 2016-01-08 17:02
Thanks.

**Closed as completed by oparoz** 2016-01-08 17:02 UTC
Labels: blue-ticket
