### ISSUE TITLE
Scrolling in desktop browsers doesn't work properly

### ISSUE THREAD

**Issue by akemper** [owncloud/gallery#506] opened 2016-02-08 12:48 UTC
With the latest versions of Owncloud and the official gallery plugin scrolling in a larger collection of pictures doesn't work. The scrollbar is showing up as expected and can be moved by some centimeters, but it doesn't cover the full amount of uploaded pictures. Instead, the last shown row of pictures get's simply horizontally cut, followed by the standard footer "ownCloud – web services under your control", without the option to move further down the view.

**Comment by oparoz** [comment] 2016-02-08 12:50
A duplicate of https://github.com/owncloud/gallery/issues/490

**Closed as completed by oparoz** 2016-02-08 12:50 UTC
Labels: duplicate
