### ISSUE TITLE
With SAFARY, If you have the option "Enforce password protection", You should be able to share link

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/gallery#399] opened 2015-10-02 11:20 UTC
### Steps to reproduce
1. Go to the Server Client with Admin
2. Go to the Sharing option 
3. Select the option "Enforce password protection"
   ![screen shot 2015-10-02 at 13 11 21](https://cloud.githubusercontent.com/assets/12032058/10245362/1cc768b6-6907-11e5-8e75-2c906b3d69b5.png)
4. Close the Admin sesion
5. Login with user1
6. Go to the Gallery
7. You have one folder with some Photos (e.g. folder call Hello)
8. Go to the folder Hello
9. Click on Share
10. Select the option Share by link
### Expected behaviour

You should be able to share link
### Actual behaviour

When you Share link, you can see the error: 
![screen shot 2015-10-02 at 13 15 46](https://cloud.githubusercontent.com/assets/12032058/10245434/bbc35fba-6907-11e5-9632-c660d98ca02f.png)
### Server configuration

Server v {"installed":true,"maintenance":false,"version":"8.2.0.7","versionstring":"8.2 beta1","edition":""}

**Comment by oparoz** [comment] 2015-10-02 11:50
@icewind1991 - Could this be related to your modifications for the checkboxes in the share dialogue?

**Comment by oparoz** [comment] 2015-10-03 12:42
@Dianafg76 - I can't reproduce using `core` master and safari iOS8. Maybe some random issue with the sharing backend?

**Comment by Dianafg76** [comment] 2015-10-05 07:09
@oparoz Hello, I tested this bug again and now it is working OK.

**Comment by oparoz** [comment] 2015-10-05 08:36
Thanks! I'll close this for now.

**Closed as completed by oparoz** 2015-10-05 08:36 UTC
Labels: bug
