### ISSUE TITLE
Not working with ownCloud 8.1

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/gallery#198] opened 2015-07-08 18:44 UTC
In console I have error:
> Firefox can't establish a connection to the server at https://***/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=home...... eventsource.js:58:0

Version 0.6.0

**Comment by jospoortvliet** [comment] 2015-07-09 14:42
could you try to fill in the template: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md

?

**Comment by nazar-pc** [comment] 2015-07-09 19:27
Sure:
### Steps to reproduce
1. Enable gallery in administration
2. Go to https://host//index.php/apps/gallery/

### Expected behaviour
See working gallery

### Actual behaviour
Infinitely spinning load icon

### Server configuration
**Operating system**: Ubuntu 14.04.2 LTS (Docker container)

**Web server:** nginx/1.4.6 (Ubuntu)

**Database:** MariaDB 10.0.20

**PHP version:** 5.5.9-1ubuntu4.11

**ownCloud version:** 8.1.0.8

**Updated from an older ownCloud or fresh install:** Upgraded from 8.0, was upgraded from 7.x

**List of activated apps:**
* Activity 2.0.1
* Deleted files 0.6.3
* Documents 0.9.0
* File Locking
* First Run Wizard 1.1
* Full Text Search 0.6.0
* PDF Viewer 0.7
* Pictures 0.6.0
* Share Files 0.6.2
* Text Editor 0.4
* Versions 1.0.6
* Video Viewer 0.1.3
* Files Move 0.8.1a
* Tasks 0.6.0
* Files Counter 0.1

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => '*',
  'passwordsalt' => '*',
  'trusted_domains' => 
  array (
    0 => '*',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => '*',
  'dbhost' => '*',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*',
  'dbpassword' => '*',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => '*',
  'mail_domain' => '*',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => '*',
  'mail_smtpport' => '587',
  'mail_smtpname' => '*',
  'mail_smtppassword' => '*',
  'forcessl' => true,
  'loglevel' => 2,
  'blacklisted_files' => 
  array (
  ),
  'theme' => '',
  'maintenance' => false,
  'secret' => '*',
  'memcache.local' => '\\OC\\Memcache\\Memcached',
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no


### Client configuration
Not relevant

### Logs
#### Web server error log
Nothing relevant

#### ownCloud log (data/owncloud.log)
Nothing relevant

#### Browser log
JS:
```
Firefox can't establish a connection to the server at https://host/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=home...... eventsource.js:58:0
```
Network:
```
520 Origin Error for URL:
https://host/index.php/apps/gallery/ajax/thumbnail/batch?token=&image=*&scale=1&square=1&requesttoken=*
```

**Comment by pasbec** [comment] 2015-07-14 20:09
Same problem here:

There seems to be a problem with a way too long Request-URI. Firefox-console shows following error messages:

    GET XHR
    https://{SERVER-ADDR}/index.php/apps/gallery/ajax/thumbnail/batch 
    [HTTP/1.1 414 Request-URI Too Long 2ms]

    Firefox kann keine Verbindung zu dem Server unter https://{SERVER-ADDR}/index.php/apps/gallery/ajax/thumbnail/batch?token=&image={HERE ARE 100+ PICTURE PATHS FOLLOWING}
    eventsource.js:58:0:
    this.source= new EventSource(src+joinChar+dataStr);

Best regards,
Pascal

**Comment by oparoz** [comment] 2015-07-14 20:23
@pasbec - You need to disable Pictures and install Gallery. You will find it in the Multimedia section of the app store from within ownCloud.

**Comment by pasbec** [comment] 2015-07-14 21:31
@oparoz - Thank you for this hint! Gallery 13.0 looks "similar" from a user point of view and seem to work flawlessly. I do not look into app changes frequently. Didn't even know about gallery, till now.
Is there actually a more "favored"  app from the oc team's side? Pictures seem to be the default - but it is broken...
Anyway, sorry for the confusion!
Best,
Pascal

**Comment by oparoz** [comment] 2015-07-14 21:42
@pasbec - Yes, looking similar was key. There was just a lot of work done in the background to make it a proper app, as opposed to something part of core and to optimise it for larger installations.
It should be the new default app in 8.2 since the official one has been broken ever since 8.0 got released.
The repository is here https://github.com/owncloud/gallery , for now.. :)

**Comment by tapete** [comment] 2015-07-17 00:00
I have the same problem that the gallery does not load any pictures and the spinning wheel is shown. It can also be seen in the demo here: https://demo.owncloud.org/index.php/apps/gallery/
I use Internet Explorer 11 on Windows 7.

**Comment by oparoz** [comment] 2015-07-17 10:13
@tapete, you need to disable Pictures, clear your cache and install Gallery from the multimedia section.

**Comment by rperezb** [comment] 2015-07-22 07:01
@carlaschroder perhaps this should be included on the documentation:
https://github.com/owncloud/gallery/issues/198#issuecomment-121371320
cc @cmonteroluque

**Comment by tapete** [comment] 2015-07-22 08:17
@oparoz  i followed your advice. But the gallery app tells me that my browser (IE11) is not supported and i should use firefox or chrome and it does not show pictures. Is this expected behaviour?

**Comment by oparoz** [comment] 2015-07-22 10:59
@tapete - On IE11, you should get pictures. Make sure you've cleared your cache. If not, then you need to tell us more about the problem here: https://github.com/owncloud/galleryplus/issues
There is a warning because we have to use workarounds for IE11 and because it's less tested than other browsers.

**Comment by oparoz** [comment] 2015-07-22 11:03
@rperezb - It's not a bad idea. Adding something to the release notes, letting users know that they can upgrade if the standard app doesn't work for them.

**Comment by oparoz** [comment] 2015-07-26 03:03
Closing.
* The IE problem has been solved both in Pictures 8.1 and Gallery 8.*
* The hanging app has been fixed in Gallery and won't be fixed in Pictures

**Closed by oparoz** 2015-07-26 03:03 UTC

**Comment by nazar-pc** [comment] 2015-07-26 11:20
@oparoz, do you want to say that officially recommended app is not working and will never be fixed? Maybe it is better to put it in trash and recommend another app instead right in 8.1.1?

**Comment by oparoz** [comment] 2015-07-26 13:07
We can't switch app mid-cycle, but we already recommend to switch in the forum and in issues when the problem the user is experiencing is major and already fixed in Gallery.

People using Firefox or Chrome, with small pictures collections, no encryption, no file locking, no external storage or cloud (s2s), no SVG, no corrupt files should be fine with Pictures.

**Comment by nazar-pc** [comment] 2015-07-26 13:28
Firefox, no encryption, local storage, no locking, fresh installation, default set of sample files - not working.

**Comment by oparoz** [comment] 2015-07-26 14:34
:S 

Please check if you still have the `520 Origin Error for URL` error and check if you also have the problem with Gallery.
