### ISSUE TITLE
Internet explorer 8 is an incompatible browser for gallery.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/gallery#318] opened 2015-09-09 16:24 UTC
### Steps to reproduce

Using internet explorer 8 do:
1. Upload some images.
2. Open gallery.
### Expected behaviour

Gallery is opened.
### Actual behaviour

It warns the user saying that browser is incompatible and doesn't load images.
### Server configuration

Operating system:
Ubuntu 14.04 LTS

Web server:
Apache

Database:
MySQL

PHP version:
5.5.9

ownCloud version: (see ownCloud admin page)
{"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":""}

Updated from an older ownCloud or fresh install:
fresh

List of activated apps:
Default ones.

Are you using external storage, if yes which one: local/smb/sftp/...
No.

Are you using encryption: 
No.
### Client configuration

Internet Explorer 8

**Comment by oparoz** [comment] 2015-09-09 22:02
It's not a bug, it was the simplest solution to match the level of support available in Pictures. The only difference is that there is now a message for the user instead of a broken app. See this ticket laying down all possible options: https://github.com/owncloud/gallery/issues/249

**Comment by jancborchardt** [comment] 2015-09-11 13:31
For reference, the issue about IE8 support is at https://github.com/owncloud/gallery/issues/228

We should try to get the Gallery working on IE8 too, not only the slideshow. @oparoz you don’t necessarily need to do that though, that’s ok. :)

**Comment by oparoz** [comment] 2015-09-11 14:17
@jancborchardt - I've done most of the work by analysing the requirements and detailing what needs to be done, so should be fairly easy for someone to implement the solution, but it's always going to be a sub-par experience.

**Comment by jancborchardt** [comment] 2015-09-11 14:41
@oparoz yup :) in the next weeks someone will likely pick that up, thanks a ton (!) for the research and work on that.

It's fine if it's not as polished on IE8 as with the other browsers, but it should work. That is, if you only use IE8 you should think everything is fine. ;)

**Comment by oparoz** [comment] 2015-09-11 15:04
:+1: :)

**Comment by oparoz** [comment] 2016-01-27 16:50
This can now be closed as IE8 support has been dropped for 9.0+

**Closed as completed by oparoz** 2016-01-27 16:50 UTC
Labels: duplicate, feature:photowall, browser:ie
