### ISSUE TITLE
Overview thumbnails not completly visible/displayed after navigating back to previous directory

### ISSUE THREAD

**Issue by nRaecheR** [owncloud/gallery#139] opened 2014-11-25 06:46 UTC
# Expected behaviour

While navigating through the gallery the overview thumbnails for all directories should always be visible/displayed. 

# Actual behaviour

When navigating to a child directory and returning to a parent directory (e.g. using the navbar) the positioning of the overview thumbnails of the child directories is incorrect leading to missing thumbnails/directories. Only a refresh (CTRL-R) of the browser will fix it until another child directory is opened. 

### Example : 
When there are 30 subfolders in the gallery all 30 overview thumbnails are displayed the first time you navigate to the folder. There are 3 rows with 10 thumbs. After navigating to one of these subfolders and returning to the parent folder only the first 10 thumbs and the last ones are displayed. The middle row seems to be missing. I suspect some kind of positioning problem, because it seems that the missing thumbs are rendered offscreen at the right of the first line.

# Steps to reproduce

* Open gallery
* Navigate to folder with lots of subfolders
* Navigate to subfolder
* Navigate back to parent folder.

# Server configuration

Owncloud 7.02/7.03

Operating system: Ubuntu 14.10

Web server: apache 2.4.10 

Database: MariaDB 5.5.30

PHP version: 5.5.12

# Client configuration

Browser: Tested with FF 33.1 and IE 11

Operating system: Linux and Windows, all versions

**Comment by oparoz** [comment] 2015-01-13 22:26
@nRaecheR - Nothing will "officially" improve for OC7, the focus is on OC8 which is 2-3 weeks away
You can try this release of the gallery app which brings all the current features of master to OC7 users:
https://github.com/interfasys/galleryplus/releases

As described in the readme, you may want to patch your ownCloud installation to fix a nasty session bug and to be able to enjoy previews of more image formats.

**Comment by nRaecheR** [comment] 2015-01-14 06:07
Thanks for your answers. Because OC8 is just some weeks ahead I think I will wait for this if there is no chance for a fix in current "stable"....

@oparoz Could you please provide a link to the readme you've mentioned with the fix for the session bug ? I can't find it in the readme of Gallery+. Thank you.

**Comment by oparoz** [comment] 2015-01-14 09:37
@nRaecheR - The README.md in the archive should have the instructions or you can look at the one online: https://github.com/interfasys/galleryplus/tree/stable7
It's only required for OC7

**Comment by nRaecheR** [comment] 2015-01-14 13:36
Ah, thank you, I've looked at the stable7 branch.

**Comment by oparoz** [comment] 2015-07-26 15:28
Closing since this is unlikely to be fixed in Pictures 8.0 and 8.1 and not reproducible in the new Gallery

**Closed by oparoz** 2015-07-26 15:28 UTC
