### ISSUE TITLE
no-show and high cpu load

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/gallery#42] opened 2015-02-27 04:48 UTC
Hi,

I get a blank page and on my server, some running processes eating all CPU:
24774 wwwrun    20   0  430424 158872  13472 R 90.03 1.942   0:31.86 httpd2-prefork
24777 wwwrun    20   0  234520  36920  12836 R 76.08 0.451   0:06.78 httpd2-prefork
24416 mysql     20   0 1765760 204048  14568 S 16.94 2.494   0:45.98 mysqld
25418 wwwrun    20   0  233756  36240  12836 S 12.29 0.443   0:01.70 httpd2-prefork

Will check in the morning if they're still eating CPU, this might be initial indexing (I have a big pic collection).

Perhaps it'd be nice to show that indexing is happening, if that is what is going on... Now I'm just mystified as to why nothing shows.

**Comment by jospoortvliet** [comment] 2015-02-27 04:48
There is nothing in the logs - anything I can do to check what's going on, let me know.

**Comment by jospoortvliet** [comment] 2015-02-27 04:49
oh and you might want to set max php to PHP 5.7 - I have 5.6 here and it didn't work until I did that :D

**Comment by jospoortvliet** [comment] 2015-02-27 10:32
Not working yet ;-)

I see that the Pictures app has the same problem: it just shows a white page.
![eight1](https://cloud.githubusercontent.com/assets/551757/6411146/00e784a0-be76-11e4-89ff-a9bc33731004.png)

**Comment by oparoz** [comment] 2015-02-28 12:07
Your main problem is probably this one https://github.com/interfasys/galleryplus/issues/17 , which can be fixed for some people by using the `performance-fixes` branch which, for now, just loads the current folder in memory before generating the first thumbnails.

Regarding the PHP version, the app is untested on 5.6, so people who know how can remove the check and help with the debugging so that the next version is compatible.
See https://github.com/interfasys/galleryplus/issues/20

**Comment by jospoortvliet** [comment] 2015-02-28 14:35
Tried the performance-fixes branch. Doesn't seem to help, still a bank screen :(

Might indeed be PHP 5.6 then... Honestly, my log is flooding with all kinds of errors at the moment, from webdav stuff to the external storage app giving 401's so stuff is broken all over. Meh.

**Comment by oparoz** [comment] 2015-02-28 17:53
I've just pushed this change if you want to give it a go?
https://github.com/interfasys/galleryplus/commit/a295b031ae54ae91da4ed5c6b5ad139986ec28e6

The preview system doesn't seem to play nice with external storage... and I'll track changes in this ticket: https://github.com/interfasys/galleryplus/issues/13

**Comment by jospoortvliet** [comment] 2015-03-03 10:42
aaaah pictures are showing up! Mostly in the subfolders, the root has less luck but there are hundreds of folders with hundreds of pics each in there...

It takes time, but it works much better now. So happy me! Now, mr @oparoz - more more more :D

If you need, I would be happy to try and supply you with some gigabytes of pictures for testing, hehe

**Comment by oparoz** [comment] 2015-03-03 16:35
I bet you see high CPU loads when sitting at the root folder and your owncloud.log should show some activity as well. Because with 500 thumbnails, the app is sending 25 requests which each generate 20 thumbnails. If you have large files which are not yet cached and are not using the "max preview" patches, it could take anything between **10 to 600 seconds per image**.

So, if you have 7 albums per row, that's 28 pictures. I think that even with the preload bug, the row will be rendered once you get the last one (can't remember). That could be **in 3-4 minutes or 30 minutes**, depending on the content of your folders. And that's **per row**, with no indication of what's going on in the user interface.
Once you go in the folder, you'll have to wait 1/4th of the time per row, unless you have sub-albums.

The amount of time it takes to generates thumbnails can be fixed in core via the patches, but in order to not frustrate the user, this has to be implemented: https://github.com/interfasys/galleryplus/issues/29

**Comment by oparoz** [comment] 2015-04-07 15:27
I'm going to close this as a duplicate of #18 . The remaining problem has to do with thumbnail generation.

**Closed as completed by oparoz** 2015-04-07 15:27 UTC
