### ISSUE TITLE
Make action menu for thumbnails extensible with plugins

### ISSUE THREAD

**Issue by Bugsbane** [owncloud/gallery#464] opened 2015-11-10 05:43 UTC
The new ... menu next to each file in the files app, is incredibly useful, and flexible. Often though, for certain folders made up of a lot of photos, I find myself using the gallery app to browse the files instead of the files app. The trouble is though, that often when I'm using the Gallery app I find myself needing to do various actions found in the ... menu, and switching back and forth between the file and gallery app constantly to do the same action for various files is very cumbersome.

I propose that we make the same ... menu, currently available in the files app available in the Gallery app, too. Specifically in the photowall view, that the ... appear in the top right of any image hovered over or long pressed. In the single image view, the ... would appear in the top right, overlaid. Given that download already exists in the ... menu, this would remove the need to have the current download arrow.
### TODO
- [ ] Action menu for thumbnails
- [ ] Import plugin system from Files
##

**Comment by oparoz** [comment] 2015-11-11 15:17
This is a duplicate of https://github.com/owncloud/gallery/issues/39

**Comment by Bugsbane** [comment] 2015-11-13 08:00
No, this is significantly different. Both issues mention a menu for actions that can be performed on images, but that's about it. Issue 39 has a specific hard list of actions. What I am proposing is that we specifically use the same files_apps that are found in the current files app menu, which is far more extendable and modular.

For example, on my install, I have the files_move app installed. The implementation in #39 would ignore this. What I'm suggesting would also make move available in the image menu, just as it's now available in the files app menu.

**Comment by oparoz** [comment] 2015-11-17 12:16
#39 doesn't have a hard list of actions, those are suggestions, based on what people have mentioned as useful.

It's not possible to have a 3 dots menu like in Files without implementing a plugins system (#128). Then every app which adds their Javascript to Files will need to be modified to also inject their code into Gallery.

So:
1. Menu
2. Plugin system
3. Convert apps

**Comment by Bugsbane** [comment] 2015-11-17 17:16
Fair enough.

**Comment by oparoz** [comment] 2016-09-04 12:14
This issue was moved to nextcloud/gallery#103

**Closed as completed by oparoz** 2016-09-04 12:14 UTC
Labels: enhancement, feature:photowall
