### ISSUE TITLE
Feature request: Create thumbnails and screen sized images immediately after upload

### ISSUE THREAD

**Issue by astroleo** [owncloud/gallery#540] opened 2016-02-28 17:35 UTC
## Feature request

**User type**: any

**User level**: any
### Description

I run owncloud 8.2.2 on a Raspberry Pi which works just fine (and thank you all for this!), but isn't terribly fast. When I share a link to a gallery it takes quite some time to browse through the gallery for the first visitor. opening the gallery, clicking on an image, then clicking the overlaid "next" arrow in the screen-sized image. I understand that opening one screen-sized image triggers the creation of the next one, but (for the Raspy) this isn't fast enough and the first user has to wait each time she clicks the "next" button.

My suggestion would be to add an option to create, right after uploading the album, the various required image sizes so that they are served quickly from the cache already for the first visitor.
### Benefit / value

For OC installations on low-power computers (e.g. Raspberry Pi) the first visitor would already be able  to smoothly scroll through an album.
### Risk / caveats

If uploading a large amount of pictures, creating the cached versions may create quite some server load. The pre-caching task should therefore be given a low priority.
### Sponsorship

I'm afraid I cannot sponsor anything yet, but I'd be happy to help developing / testing this new feature if an expert could provide me with some background on how caching works in OC. 

**Are you a developer willing to implement this feature?**: yes

**Can you sponsor the development of this feature or do you know somewone who can?**: no

**Comment by oparoz** [comment] 2016-02-28 17:49
I'm marking this as a duplicate of #18. I've moved your OP over.

**Closed as completed by oparoz** 2016-02-28 17:49 UTC
Labels: duplicate
