### ISSUE TITLE
galleryfileaction.js causes redirect loop if used in unauthenticaed route

### ISSUE THREAD

**Issue by rullzer** [owncloud/gallery#619] opened 2016-03-23 15:03 UTC
### Steps to reproduce
1. Have an app `files_foo` that has a public route.
2. Access that route
### Expected behaviour

All is fine
### Actual behaviour

Page gets reloaded over and over again.

This happens because of 
1. https://github.com/owncloud/gallery/blob/master/appinfo/app.php#L65
2. which loads https://github.com/owncloud/gallery/blob/master/appinfo/app.php#L75
3. which in turn does https://github.com/owncloud/gallery/blob/master/js/galleryfileaction.js#L214-L218
4. Which fails with a 401
5. which is then caught globally and reloads

Easies solution is probabaly to set `allowAuthErrors` https://github.com/owncloud/core/blob/v9.0.0/core/js/js.js#L1442

**Comment by PVince81** [comment] 2016-03-23 15:15
Why is "galleryfileaction.js" even returning a 401 ? A 404 or 500 I would understand.
Is the code loading the file missing authentication info / cookies ?

**Comment by rullzer** [comment] 2016-03-23 15:19
@PVince81 it is requesting: `../apps/gallery/config?extramediatypes=1` which is an authenticated route...

**Comment by oparoz** [comment] 2016-03-23 16:16
It's probably easier to solve if there is a standard way to retrieve a token to fix this line:
https://github.com/owncloud/gallery/blob/master/js/galleryfileaction.js#L22

**Comment by PVince81** [comment] 2016-03-24 11:27
Would this regexp https://github.com/owncloud/gallery/blob/master/appinfo/app.php#L65 also match other apps like "files_xxx" ?

**Comment by PVince81** [comment] 2016-03-24 11:27
This approach can be used now to only load scripts in the files app: https://github.com/owncloud/core/blob/v8.2.2/apps/files_sharing/appinfo/app.php#L57

**Comment by oparoz** [comment] 2016-03-24 11:30
> Would this regexp https://github.com/owncloud/gallery/blob/master/appinfo/app.php#L65 also match other apps like "files_xxx" ?

I'll check, but this may very well be the case

> This approach can be used now to only load scripts in the files app: https://github.com/owncloud/core/blob/v8.2.2/apps/files_sharing/appinfo/app.php#L57

It can't be used yet. See: https://github.com/owncloud/core/issues/22328

**Comment by oparoz** [comment] 2016-03-24 11:44
@PVince81 - The regexp doesn't match `files_xxx`

**Comment by oparoz** [comment] 2016-03-24 11:45
But if that app has a public, short URL using `/s/`, then yes, the script will be loaded.

**Comment by rullzer** [comment] 2016-03-24 11:55
> @PVince81 - The regexp doesn't match files_xxx

Yes it does...
or rather `../apps/files_xxx...`

**Comment by oparoz** [comment] 2016-03-24 12:25
Not according to this:
https://regex101.com/r/dP4iS2/1

**Comment by rullzer** [comment] 2016-03-24 13:32
@oparoz that link shows it matches here...

**Comment by oparoz** [comment] 2016-03-24 13:34
In my browser:

"No match groups were extracted."

**Comment by oparoz** [comment] 2016-03-24 13:36
From the PHP doc:

"$matches[1] will have the text that matched the first captured parenthesized subpattern"

Am I reading this wrong?

**Comment by rullzer** [comment] 2016-03-24 15:54
@oparoz well see: https://3v4l.org/eVIbr

and

`preg_match() returns 1 if the pattern matches given subject, 0 if it does not, or FALSE if an error occurred.`

Anyway... lets solve with a whitelist not blacklist ;)

**Comment by oparoz** [comment] 2016-03-24 16:05
Thanks for that website, that will be handy :)

**Comment by PVince81** [comment] 2016-03-24 16:08
Linking with PR here https://github.com/owncloud/gallery/pull/620

**Comment by oparoz** [comment] 2016-03-24 16:46
And your backport for stable9 #622

**Comment by oparoz** [comment] 2016-03-26 14:23
There is a regression.
1. Open Gallery
2. Click on an album
3. Switch to Files (button top-right)

The slideshow won't work and the Gallery button is gone.

The new regexp doesn't work for URLs which look like this: `files?dir`, it always expects a `/` before the parameters.

**Comment by oparoz** [comment] 2016-03-26 14:30
~~Fix is in #628~~ Never mind that goes back to square one. I'm reverting #620 .

**Comment by oparoz** [comment] 2016-03-29 12:46
So, is there a reliable way to get a public share token via Javascript?

**Comment by rullzer** [comment] 2016-03-29 13:20
@oparoz not that I know of

**Comment by oparoz** [comment] 2016-03-29 13:26
OK, so it's a bit of a problem, because apparently, there can be non-public apps/templates hiding behind a public URL.

**Comment by rullzer** [comment] 2016-03-29 13:32
so there is the `<input type="hidden" name="sharingToken" value="RhPiMUeUcr6QP7r" id="sharingToken">`

Which you can of course fetch

**Comment by oparoz** [comment] 2016-03-29 13:40
Yep, that's exactly what I'm doing but files_drop doesn't seem to have that and neither does the 404 page when a share isn't available any more.

**Comment by rullzer** [comment] 2016-03-29 16:00
Ah mmm. well that might be a more long term fix. ( @PVince81 ).
For now lets try to list all the possible links that we need to handle so we can create one or multiple regexes to match against.

I'd say we should try to match.
- `/apps\/files$/`
- `/apps\/files_sharing$/`
- `%apps\/files[/?]%*
- `%apps\/files_sharing[/?]%*

Wich we can of course combine into:
- `/apps\/files(_sharing)?$/`
- `%apps/files(_sharing)?[/?]%`

**Comment by oparoz** [comment] 2016-03-29 21:46
Works for me. The problem with public URLs can only be solved via owncloud/core#22328

**Comment by oparoz** [comment] 2016-04-17 13:18
This was included in 9.0.1

**Closed as completed by oparoz** 2016-04-17 13:18 UTC
Labels: bug
