### ISSUE TITLE
Sorting icons messed up

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/gallery#650] opened 2016-05-14 06:14 UTC
This is what I see in 9.0.2:
![capture du 2016-05-14 08-12-47](https://cloud.githubusercontent.com/assets/925062/15266614/b96bf83a-19ab-11e6-9d1a-8f186b81d3ac.png)

cc @oparoz @owncloud/designers any idea here? Compression maybe … seems like they are layered over a second time, but upside down.

**Comment by jancborchardt** [comment] 2016-05-14 06:14
Aaah I guess cause of the CSS/JS effect of the sorting icon switching up/down when changing? Not sure though. Only the arrow should change directions.

**Comment by oparoz** [comment] 2016-05-14 10:33
I can't reproduce. Does it happen a 100% of the time?
It's probably due to a JS error which stops the execution of the script, so check the browser log.

**Comment by skjnldsv** [comment] 2016-05-14 11:19
Can't reproduce either! What browser? i supposed you tried an ignore cache reload?

**Comment by tempico** [comment] 2016-05-19 16:19
adblock?

**Comment by oparoz** [comment] 2016-06-06 14:55
Closing since nobody can reproduce. Could be a problem with a specific browser version.

**Closed as completed by oparoz** 2016-06-06 14:55 UTC
Labels: bug, design
