### ISSUE TITLE
Undefinex index image at in /apps/gallery/ajax/batch.php#13

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/gallery#256] opened 2015-07-30 11:46 UTC
### Steps to reproduce
1. Open Pictures App in OwnCloud 8.1
2. Gallery is loading and loading
3. Check admin log for error
### Expected behaviour

Gallery should load and display images
### Actual behaviour

Nothing, it loads and loads and loads
### Server configuration

**Operating system**:
Apache-Version  2.2.29
PHP-Version 5.4.40
MySQL-Version   5.6.23
Architektur x86_64
Betriebssystem  linux
Pfad zu sendmail    /usr/sbin/sendmail
Pfad zu Perl    /usr/bin/perl
Kernel-Version  2.6.32-042stab108.2

**ownCloud version:**  8.1.0 stable
**Updated from an older ownCloud or fresh install:**
Upgraded from lates 8.0.4 version
Transactional File Locking is disabled.

**List of activated apps:**

```
Default apps:
Deleted files 0.6.3
External Sites 1.2
External user support 0.4
File Locking
First Run Wizard 1.1
PDF Viewer 0.7
Pictures 0.6.0
Share Files 0.6.2
Text Editor 0.4
Updater 0.6
Versions 1.0.6
Video Viewer 0.1.3
```

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxx',
  'datadirectory' => '/home/xxxxxx/public_html/data',
  'dbtype' => 'mysql',
  'version' => '8.1.0.8',
  'dbname' => 'xxxxxxxxxxxxxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxxxxxxxxxxx',
  'dbpassword' => 'xxxxxxxxxxxxxxx',
  'installed' => true,
  'forcessl' => true,
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
  'loglevel' => 0,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'appstoreenabled' => true,
  'appstoreurl' => 'https://api.owncloud.com/v1',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/home/xxxxxxxx/public_html/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'appcodechecker' => true,
  'enable_previews' => true,
  'theme' => '',
  'maintenance' => false,
  'updatechecker' => true,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'trusted_domains' => 
  array (
    0 => 'xxxxxxxxxxx.xxxxxxxxxxxxx.xxxxxxxxxxxxxxxxxxxx',
  ),
  'secret' => 'xxxxxxxxxxxxxx',
);



```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no, only Forece SSL
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:** Firefox 39

**Operating system:**
Windows 7 Prof x64, 
#### Web server error log

```
[Thu Jul 30 13:26:18 2015] [crit] [ client xxx][ (13)Permission denied: /home/xxxxxxxx/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
```
#### ownCloud log (data/owncloud.log)

```
{"reqId":"VboJjpT7rpwAAEtl8t0AAAAI","remoteAddr":"xxxxxxxxxxxxxx","app":"PHP","message":"Undefined index: image at \/home\/xxxxxxxxxxxx\/public_html\/apps\/gallery\/ajax\/batch.php#13","level":3,"time":"July 30, 2015 13:25:02","method":"GET","url":"\/index.php\/apps\/gallery\/ajax\/thumbnail\/batch?token=&image=DabaUebungen%2F2014-08-16.jpg [names of several image files]  &scale=1&square=1&requesttoken=8zAA24n5UCYui5lVj3DpvBw5q7HwtU"}
```
#### Browser log

```
13:44:20.827 GET 
https://xxxxx.xxxxx.xxxx/index.php/apps/gallery/ [HTTP/1.1 200 OK 449ms]
13:44:21.505 GET 
https://xxxxx.xxxxx.xxxx/index.php/core/js/oc.js [HTTP/1.1 200 OK 291ms]
13:44:21.712 Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
13:44:22.635 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://xxxxx.xxxxx.xxxx 'unsafe-eval'"). gallery
13:44:22.732 getPreventDefault() sollte nicht mehr verwendet werden. Verwenden Sie stattdessen defaultPrevented. jquery.min.js:5:0
13:44:22.860 GET 
XHR 
https://xxxxx.xxxxx.xxxx/cron.php [HTTP/1.1 200 OK 4472ms]
13:44:22.860 GET 
XHR 
https://xxxxx.xxxxx.xxxx/index.php/apps/gallery/ajax/images [HTTP/1.1 200 OK 2477ms]
13:44:22.861 GET 
XHR 
https://xxxxx.xxxxx.xxxx/index.php/avatar/xxxxxxxxxx_admin/128 [HTTP/1.1 200 OK 2235ms]
13:44:25.356 GET 
XHR 
https://xxxxx.xxxxx.xxxx/index.php/apps/gallery/ajax/gallery [HTTP/1.1 200 OK 293ms]
13:44:25.357 GET 
XHR 
https://xxxxx.xxxxx.xxxx/index.php/apps/gallery/ajax/thumbnail/batch [HTTP/1.1 200 OK 406ms]
13:44:25.740 TypeError: path.substr is not a function
```

**Comment by oparoz** [comment] 2015-07-30 12:33
Thanks a lot for the report, however this is unlikely to be fixed in Pictures as most of these bugs have already been fixed in Gallery.

Please disable Pictures, clear your cache and install Gallery from the multimedia section. If you're still experiencing the problem, then report back here.

**Comment by Siedlerchr** [comment] 2015-07-30 15:39
@oparoz  Thanks for your info. I did install Gallery with succes and it works fine.
Mabye Pictures should be marked as "deprecated" in the ownncloud app list-

**Comment by oparoz** [comment] 2015-07-30 15:55
@Siedlerchr - The problem is that it's the only app shipping with ownCloud, so it's kind of difficult to tell users right away that they have to install something else, especially since in the next release, Pictures will be replaced with Gallery, so people will have to switch back (if they want since Gallery+ will still exist and be updated more frequently than Gallery)

I'm open to suggestions if you can think of better ways to handle the situation. There is already a forum thread advising people to switch.

**Closed as completed by oparoz** 2015-07-30 15:55 UTC
Labels: bug, Legacy
