### ISSUE TITLE
Pinch to zoom in slideshow

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/gallery#526] opened 2016-02-18 15:39 UTC
Allow pinch to zoom on mobile devices in slideshow. Currently this is not possible.

To handle the quality of the image we could maybe download the original image once the pinch to zoom is started and replace it once it's finished to make the UX superb.

I just got many complains, that you need to download an image first to zoom in.

cc @owncloud/designers

**Comment by oparoz** [comment] 2016-02-18 15:42
Duplicate of https://github.com/owncloud/gallery/issues/263

It currently only works on iOS. Can be fixed by either patching Bigshot or changing slideshow engine.

**Closed as completed by oparoz** 2016-02-18 15:42 UTC
Labels: duplicate, enhancement
