### ISSUE TITLE
No possibility to send an email in share dialog

### ISSUE THREAD

**Issue by sonymaster** [owncloud/gallery#213] opened 2015-07-14 10:56 UTC
If you open the share dialog from the top right share button, you can share the gallery with OC users or/and as Link. But the possibility to send an email with share infos is not displayed like in the Files app.

**Comment by oparoz** [comment] 2015-07-14 12:10
You're correct, thanks for notifying us.

**Comment by oparoz** [comment] 2015-09-14 16:00
@rullzer @PVince81 - Is there something special to do to get the share by email section in the share dropdown?

**Comment by imjalpreet** [comment] 2016-03-09 08:16
@oparoz Can you please give little more detail regarding this? I am not exactly able to figure out what the problem is. I didn't understand the line : "_**..possibility to send an email with share infos..**_". Thanks!

**Comment by oparoz** [comment] 2016-03-09 09:52
If you compare the dialogue in Gallery with the one in Files, you'll notice that you cannot send an email in Gallery after having created a share or a public link.
There are screenshots in #498.

Also, in `share.js` I've commented out the code as it's not in use. You need to uncomment the parts relevant to email sharing and update it to make it work like the rest of the class.

**Comment by oparoz** [comment] 2016-03-09 14:11
This commit should help you see the changes made to the ajax calls: https://github.com/owncloud/gallery/commit/48cf8534c9ff9b8ca6eb88b2720e33651e532e3b#diff-b3a827de53066e0a69e83addf18ddd46

**Comment by imjalpreet** [comment] 2016-03-09 15:48
@oparoz Thanks! I will come up with a solution as soon as possible. I am trying to understand the flow right now.

**Comment by oparoz** [comment] 2016-03-09 18:05
That class is a pita... This one is easier to understand because it doesn't have all the UI stuff mixed up:
https://github.com/owncloud/core/blob/master/core/js/shareitemmodel.js

Eventually, we should migrate to that, using Backbone.

**Comment by imjalpreet** [comment] 2016-03-11 11:31
![error](https://cloud.githubusercontent.com/assets/6432146/13701822/4e15694a-e7b0-11e5-86ae-6a712bcf0d39.png)
@oparoz I wanted to ask you a question. When I am trying to send a mail from files app, I am getting an error message(attached screenshot). Can you tell me do we have to setup mail before this? Thanks!

**Comment by oparoz** [comment] 2016-03-11 11:56
I don't see the screenshot, but look in the admin settings. There you can authorise emails to be sent.

**Comment by imjalpreet** [comment] 2016-03-11 12:11
@oparoz No problems. I have figured out how to do it. Thanks!

**Comment by oparoz** [comment] 2016-03-11 12:35
Ah, good :)

**Comment by oparoz** [comment] 2016-03-11 12:37
And if admin settings are involved, don't forget to add that to your test plan. It would have to be tested with and without them in order to see if the interface adapts to the settings.

**Comment by oparoz** [comment] 2016-03-11 17:56
@sonymaster - Fix is in #586

**Comment by imjalpreet** [comment] 2016-03-20 13:26
Fix in #586

**Closed as completed by imjalpreet** 2016-03-20 13:26 UTC
Labels: enhancement, coder wanted, feature:sharing
